### ISSUE TITLE
Search bar not triggering search on button click

### ISSUE THREAD

**Issue by s-shemmee** [shemmee/React-Weather-App#1]
The current implementation of the search bar component does not trigger the search function when the search button is clicked. The search function is only triggered when the Enter key is pressed. This behavior is inconsistent with the desired functionality, where the search should be performed regardless of whether the Enter key is pressed or the search button is clicked.

This issue requires updating the code to ensure that the search function is called correctly when the search button is clicked, in addition to triggering it on pressing Enter.

**Comment by Thorfin69** [comment]
Hii there i fixed that issue on your website i just updated search function and added event handler in SearchEngine component


#New search funtion 
```
const search = async (event) => {
    event.preventDefault();
    if (event.type === "click" || (event.type === "keypress" && event.key === "Enter")) {
      if (!query) return;

      setWeather({ ...weather, loading: true });
      const apiKey = "b03a640e5ef6980o4da35b006t5f2942";
      const url = `https://api.shecodes.io/weather/v1/current?query=${query}&key=${apiKey}`;

      try {
        const res = await axios.get(url);
        console.log("res", res);
        setWeather({ data: res.data, loading: false, error: false });
      } catch (error) {
        setWeather({ ...weather, data: {}, error: true });
        console.log("error", error);
      }
    }
  };
```

# for SearchEngine component i added  
onKeyPress={handleKeyPress}

```
<input
        type="text"
        className="city-search"
        placeholder="enter city name"
        name="query"
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        onKeyPress={handleKeyPress}
      />
```
# this is the handleKeyPress function
 ```
 const handleKeyPress = (e) => {
    if (e.key === 'Enter') {
      search(e);
    }
  };
```


 # in button i added 
`onCLick={search}
`
` <button onClick={search}><i className="fas fa-search" style={{ fontSize: "18px" }}></i></button>`

it fixed

https://github.com/user-attachments/assets/52aff9a7-2306-4e59-9167-cdc4e81e2207
