### ISSUE TITLE
Request for Contribution to add a Dark Mode Toggle Button in the WebApp.

### ISSUE THREAD

**Issue by prakshark** [shemmee/React-Weather-App#3]
## Hi Shemmee!

I came across your project on "The Full Stack", and really liked your project. I would like to contribute to the project by adding a Dark Mode Toggle Button into this amazing Web Application. 
If you are okay with it, I will begin working on the project. And if you like it, you may merge my Pull Request into the Main Branch.

Waiting in anticipation.
Regards.
@prakshark

**Comment by s-shemmee** [comment]
Hi @prakshark,

Thank you so much for showing interest in contributing to my project! I’d love to see what you come up with for the Dark Mode Toggle Button.

Feel free to go ahead and start working on it. I’m looking forward to reviewing your implementation. Once you're done, just submit the pull request, and I'll review it as soon as possible.

If you have any questions or need any further guidance, don't hesitate to reach out.

Thanks again for contributing!
